---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
- apiGroups:
  - dns.packet.fail
  resources:
  - clusters
  - zones
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dns.packet.fail
  resources:
  - clusters/status
  - zones/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - dns.packet.fail
  resources:
  - zones/finalizers
  verbs:
  - update
