---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  - secrets
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dns.packet.fail
  resources:
  - blocklists
  - records
  - serversettings
  - zones
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dns.packet.fail
  resources:
  - blocklists/finalizers
  - records/finalizers
  - serversettings/finalizers
  - technitiumclusters/finalizers
  - zones/finalizers
  verbs:
  - update
- apiGroups:
  - dns.packet.fail
  resources:
  - blocklists/status
  - records/status
  - serversettings/status
  - technitiumclusters/status
  - zones/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - dns.packet.fail
  resources:
  - technitiumclusters
  verbs:
  - get
  - list
  - patch
  - update
  - watch
