## Append samples of your project ##
resources:
- dns_v1alpha1_zone.yaml
- dns_v1alpha1_technitiumcluster.yaml
- dns_v1alpha1_record.yaml
- dns_v1alpha1_serversettings.yaml
- dns_v1alpha1_blocklist.yaml
- dns_v1alpha1_dnssec.yaml
- dns_v1alpha1_dnsapp.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
