//go:build !ignore_autogenerated

/*
Copyright (c) 2026 Chris

Licensed under the MIT License. See the LICENSE file in the project root for
the full license text.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Blocklist) DeepCopyInto(out *Blocklist) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Blocklist.
func (in *Blocklist) DeepCopy() *Blocklist {
	if in == nil {
		return nil
	}
	out := new(Blocklist)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Blocklist) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BlocklistList) DeepCopyInto(out *BlocklistList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Blocklist, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BlocklistList.
func (in *BlocklistList) DeepCopy() *BlocklistList {
	if in == nil {
		return nil
	}
	out := new(BlocklistList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BlocklistList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BlocklistSpec) DeepCopyInto(out *BlocklistSpec) {
	*out = *in
	out.ServerRef = in.ServerRef
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.BlockListURLs != nil {
		in, out := &in.BlockListURLs, &out.BlockListURLs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.UpdateIntervalHours != nil {
		in, out := &in.UpdateIntervalHours, &out.UpdateIntervalHours
		*out = new(int32)
		**out = **in
	}
	if in.BlockingType != nil {
		in, out := &in.BlockingType, &out.BlockingType
		*out = new(BlockingType)
		**out = **in
	}
	if in.AllowedDomains != nil {
		in, out := &in.AllowedDomains, &out.AllowedDomains
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.BlockedDomains != nil {
		in, out := &in.BlockedDomains, &out.BlockedDomains
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BlocklistSpec.
func (in *BlocklistSpec) DeepCopy() *BlocklistSpec {
	if in == nil {
		return nil
	}
	out := new(BlocklistSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BlocklistStatus) DeepCopyInto(out *BlocklistStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AppliedBlockListURLs != nil {
		in, out := &in.AppliedBlockListURLs, &out.AppliedBlockListURLs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AppliedAllowedDomains != nil {
		in, out := &in.AppliedAllowedDomains, &out.AppliedAllowedDomains
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AppliedBlockedDomains != nil {
		in, out := &in.AppliedBlockedDomains, &out.AppliedBlockedDomains
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BlocklistStatus.
func (in *BlocklistStatus) DeepCopy() *BlocklistStatus {
	if in == nil {
		return nil
	}
	out := new(BlocklistStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CacheSettings) DeepCopyInto(out *CacheSettings) {
	*out = *in
	if in.ServeStale != nil {
		in, out := &in.ServeStale, &out.ServeStale
		*out = new(bool)
		**out = **in
	}
	if in.ServeStaleTTLSeconds != nil {
		in, out := &in.ServeStaleTTLSeconds, &out.ServeStaleTTLSeconds
		*out = new(int32)
		**out = **in
	}
	if in.MaximumRecordTTLSeconds != nil {
		in, out := &in.MaximumRecordTTLSeconds, &out.MaximumRecordTTLSeconds
		*out = new(int32)
		**out = **in
	}
	if in.MinimumRecordTTLSeconds != nil {
		in, out := &in.MinimumRecordTTLSeconds, &out.MinimumRecordTTLSeconds
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CacheSettings.
func (in *CacheSettings) DeepCopy() *CacheSettings {
	if in == nil {
		return nil
	}
	out := new(CacheSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DHCPReservation) DeepCopyInto(out *DHCPReservation) {
	*out = *in
	if in.HostName != nil {
		in, out := &in.HostName, &out.HostName
		*out = new(string)
		**out = **in
	}
	if in.Comments != nil {
		in, out := &in.Comments, &out.Comments
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DHCPReservation.
func (in *DHCPReservation) DeepCopy() *DHCPReservation {
	if in == nil {
		return nil
	}
	out := new(DHCPReservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DHCPScope) DeepCopyInto(out *DHCPScope) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DHCPScope.
func (in *DHCPScope) DeepCopy() *DHCPScope {
	if in == nil {
		return nil
	}
	out := new(DHCPScope)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DHCPScope) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DHCPScopeList) DeepCopyInto(out *DHCPScopeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DHCPScope, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DHCPScopeList.
func (in *DHCPScopeList) DeepCopy() *DHCPScopeList {
	if in == nil {
		return nil
	}
	out := new(DHCPScopeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DHCPScopeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DHCPScopeSpec) DeepCopyInto(out *DHCPScopeSpec) {
	*out = *in
	out.ServerRef = in.ServerRef
	if in.RouterAddress != nil {
		in, out := &in.RouterAddress, &out.RouterAddress
		*out = new(string)
		**out = **in
	}
	if in.DNSServers != nil {
		in, out := &in.DNSServers, &out.DNSServers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.LeaseTimeDays != nil {
		in, out := &in.LeaseTimeDays, &out.LeaseTimeDays
		*out = new(int32)
		**out = **in
	}
	if in.LeaseTimeHours != nil {
		in, out := &in.LeaseTimeHours, &out.LeaseTimeHours
		*out = new(int32)
		**out = **in
	}
	if in.LeaseTimeMinutes != nil {
		in, out := &in.LeaseTimeMinutes, &out.LeaseTimeMinutes
		*out = new(int32)
		**out = **in
	}
	if in.DomainName != nil {
		in, out := &in.DomainName, &out.DomainName
		*out = new(string)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Reservations != nil {
		in, out := &in.Reservations, &out.Reservations
		*out = make([]DHCPReservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DHCPScopeSpec.
func (in *DHCPScopeSpec) DeepCopy() *DHCPScopeSpec {
	if in == nil {
		return nil
	}
	out := new(DHCPScopeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DHCPScopeStatus) DeepCopyInto(out *DHCPScopeStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AppliedReservations != nil {
		in, out := &in.AppliedReservations, &out.AppliedReservations
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DHCPScopeStatus.
func (in *DHCPScopeStatus) DeepCopy() *DHCPScopeStatus {
	if in == nil {
		return nil
	}
	out := new(DHCPScopeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSApp) DeepCopyInto(out *DNSApp) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSApp.
func (in *DNSApp) DeepCopy() *DNSApp {
	if in == nil {
		return nil
	}
	out := new(DNSApp)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DNSApp) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSAppList) DeepCopyInto(out *DNSAppList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DNSApp, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSAppList.
func (in *DNSAppList) DeepCopy() *DNSAppList {
	if in == nil {
		return nil
	}
	out := new(DNSAppList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DNSAppList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSAppSpec) DeepCopyInto(out *DNSAppSpec) {
	*out = *in
	out.ServerRef = in.ServerRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSAppSpec.
func (in *DNSAppSpec) DeepCopy() *DNSAppSpec {
	if in == nil {
		return nil
	}
	out := new(DNSAppSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSAppStatus) DeepCopyInto(out *DNSAppStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSAppStatus.
func (in *DNSAppStatus) DeepCopy() *DNSAppStatus {
	if in == nil {
		return nil
	}
	out := new(DNSAppStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSSEC) DeepCopyInto(out *DNSSEC) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSSEC.
func (in *DNSSEC) DeepCopy() *DNSSEC {
	if in == nil {
		return nil
	}
	out := new(DNSSEC)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DNSSEC) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSSECList) DeepCopyInto(out *DNSSECList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DNSSEC, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSSECList.
func (in *DNSSECList) DeepCopy() *DNSSECList {
	if in == nil {
		return nil
	}
	out := new(DNSSECList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DNSSECList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSSECSpec) DeepCopyInto(out *DNSSECSpec) {
	*out = *in
	out.ServerRef = in.ServerRef
	if in.HashAlgorithm != nil {
		in, out := &in.HashAlgorithm, &out.HashAlgorithm
		*out = new(DNSSECHashAlgorithm)
		**out = **in
	}
	if in.KSKKeySize != nil {
		in, out := &in.KSKKeySize, &out.KSKKeySize
		*out = new(int32)
		**out = **in
	}
	if in.ZSKKeySize != nil {
		in, out := &in.ZSKKeySize, &out.ZSKKeySize
		*out = new(int32)
		**out = **in
	}
	if in.Curve != nil {
		in, out := &in.Curve, &out.Curve
		*out = new(DNSSECCurve)
		**out = **in
	}
	if in.NSEC3Iterations != nil {
		in, out := &in.NSEC3Iterations, &out.NSEC3Iterations
		*out = new(int32)
		**out = **in
	}
	if in.NSEC3SaltLength != nil {
		in, out := &in.NSEC3SaltLength, &out.NSEC3SaltLength
		*out = new(int32)
		**out = **in
	}
	if in.DNSKeyTTL != nil {
		in, out := &in.DNSKeyTTL, &out.DNSKeyTTL
		*out = new(int32)
		**out = **in
	}
	if in.ZSKRolloverDays != nil {
		in, out := &in.ZSKRolloverDays, &out.ZSKRolloverDays
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSSECSpec.
func (in *DNSSECSpec) DeepCopy() *DNSSECSpec {
	if in == nil {
		return nil
	}
	out := new(DNSSECSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSSECStatus) DeepCopyInto(out *DNSSECStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSSECStatus.
func (in *DNSSECStatus) DeepCopy() *DNSSECStatus {
	if in == nil {
		return nil
	}
	out := new(DNSSECStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ForwarderProxy) DeepCopyInto(out *ForwarderProxy) {
	*out = *in
	if in.Address != nil {
		in, out := &in.Address, &out.Address
		*out = new(string)
		**out = **in
	}
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(int32)
		**out = **in
	}
	if in.Username != nil {
		in, out := &in.Username, &out.Username
		*out = new(string)
		**out = **in
	}
	if in.Password != nil {
		in, out := &in.Password, &out.Password
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ForwarderProxy.
func (in *ForwarderProxy) DeepCopy() *ForwarderProxy {
	if in == nil {
		return nil
	}
	out := new(ForwarderProxy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ForwarderSettings) DeepCopyInto(out *ForwarderSettings) {
	*out = *in
	if in.Addresses != nil {
		in, out := &in.Addresses, &out.Addresses
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Protocol != nil {
		in, out := &in.Protocol, &out.Protocol
		*out = new(ForwarderProtocol)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ForwarderSettings.
func (in *ForwarderSettings) DeepCopy() *ForwarderSettings {
	if in == nil {
		return nil
	}
	out := new(ForwarderSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoggingSettings) DeepCopyInto(out *LoggingSettings) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.LogQueries != nil {
		in, out := &in.LogQueries, &out.LogQueries
		*out = new(bool)
		**out = **in
	}
	if in.UseLocalTime != nil {
		in, out := &in.UseLocalTime, &out.UseLocalTime
		*out = new(bool)
		**out = **in
	}
	if in.MaxFileDays != nil {
		in, out := &in.MaxFileDays, &out.MaxFileDays
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoggingSettings.
func (in *LoggingSettings) DeepCopy() *LoggingSettings {
	if in == nil {
		return nil
	}
	out := new(LoggingSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObservedServerSettings) DeepCopyInto(out *ObservedServerSettings) {
	*out = *in
	if in.Forwarders != nil {
		in, out := &in.Forwarders, &out.Forwarders
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.RecursionNetworkACL != nil {
		in, out := &in.RecursionNetworkACL, &out.RecursionNetworkACL
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ServeStale != nil {
		in, out := &in.ServeStale, &out.ServeStale
		*out = new(bool)
		**out = **in
	}
	if in.ServeStaleTTLSeconds != nil {
		in, out := &in.ServeStaleTTLSeconds, &out.ServeStaleTTLSeconds
		*out = new(int32)
		**out = **in
	}
	if in.CacheMaximumRecordTTLSeconds != nil {
		in, out := &in.CacheMaximumRecordTTLSeconds, &out.CacheMaximumRecordTTLSeconds
		*out = new(int32)
		**out = **in
	}
	if in.CacheMinimumRecordTTLSeconds != nil {
		in, out := &in.CacheMinimumRecordTTLSeconds, &out.CacheMinimumRecordTTLSeconds
		*out = new(int32)
		**out = **in
	}
	if in.LoggingEnabled != nil {
		in, out := &in.LoggingEnabled, &out.LoggingEnabled
		*out = new(bool)
		**out = **in
	}
	if in.LogQueries != nil {
		in, out := &in.LogQueries, &out.LogQueries
		*out = new(bool)
		**out = **in
	}
	if in.UseLocalTime != nil {
		in, out := &in.UseLocalTime, &out.UseLocalTime
		*out = new(bool)
		**out = **in
	}
	if in.MaxLogFileDays != nil {
		in, out := &in.MaxLogFileDays, &out.MaxLogFileDays
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObservedServerSettings.
func (in *ObservedServerSettings) DeepCopy() *ObservedServerSettings {
	if in == nil {
		return nil
	}
	out := new(ObservedServerSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Record) DeepCopyInto(out *Record) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Record.
func (in *Record) DeepCopy() *Record {
	if in == nil {
		return nil
	}
	out := new(Record)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Record) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RecordList) DeepCopyInto(out *RecordList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Record, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RecordList.
func (in *RecordList) DeepCopy() *RecordList {
	if in == nil {
		return nil
	}
	out := new(RecordList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RecordList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RecordSpec) DeepCopyInto(out *RecordSpec) {
	*out = *in
	out.ServerRef = in.ServerRef
	if in.TTL != nil {
		in, out := &in.TTL, &out.TTL
		*out = new(int32)
		**out = **in
	}
	if in.Priority != nil {
		in, out := &in.Priority, &out.Priority
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RecordSpec.
func (in *RecordSpec) DeepCopy() *RecordSpec {
	if in == nil {
		return nil
	}
	out := new(RecordSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RecordStatus) DeepCopyInto(out *RecordStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RecordStatus.
func (in *RecordStatus) DeepCopy() *RecordStatus {
	if in == nil {
		return nil
	}
	out := new(RecordStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RecursionSettings) DeepCopyInto(out *RecursionSettings) {
	*out = *in
	if in.NetworkACL != nil {
		in, out := &in.NetworkACL, &out.NetworkACL
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RecursionSettings.
func (in *RecursionSettings) DeepCopy() *RecursionSettings {
	if in == nil {
		return nil
	}
	out := new(RecursionSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretReference) DeepCopyInto(out *SecretReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretReference.
func (in *SecretReference) DeepCopy() *SecretReference {
	if in == nil {
		return nil
	}
	out := new(SecretReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServerSettings) DeepCopyInto(out *ServerSettings) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServerSettings.
func (in *ServerSettings) DeepCopy() *ServerSettings {
	if in == nil {
		return nil
	}
	out := new(ServerSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ServerSettings) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServerSettingsList) DeepCopyInto(out *ServerSettingsList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ServerSettings, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServerSettingsList.
func (in *ServerSettingsList) DeepCopy() *ServerSettingsList {
	if in == nil {
		return nil
	}
	out := new(ServerSettingsList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ServerSettingsList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServerSettingsSpec) DeepCopyInto(out *ServerSettingsSpec) {
	*out = *in
	out.ServerRef = in.ServerRef
	if in.Forwarders != nil {
		in, out := &in.Forwarders, &out.Forwarders
		*out = new(ForwarderSettings)
		(*in).DeepCopyInto(*out)
	}
	if in.Recursion != nil {
		in, out := &in.Recursion, &out.Recursion
		*out = new(RecursionSettings)
		(*in).DeepCopyInto(*out)
	}
	if in.Cache != nil {
		in, out := &in.Cache, &out.Cache
		*out = new(CacheSettings)
		(*in).DeepCopyInto(*out)
	}
	if in.Logging != nil {
		in, out := &in.Logging, &out.Logging
		*out = new(LoggingSettings)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServerSettingsSpec.
func (in *ServerSettingsSpec) DeepCopy() *ServerSettingsSpec {
	if in == nil {
		return nil
	}
	out := new(ServerSettingsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServerSettingsStatus) DeepCopyInto(out *ServerSettingsStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Observed != nil {
		in, out := &in.Observed, &out.Observed
		*out = new(ObservedServerSettings)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServerSettingsStatus.
func (in *ServerSettingsStatus) DeepCopy() *ServerSettingsStatus {
	if in == nil {
		return nil
	}
	out := new(ServerSettingsStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TechnitiumCluster) DeepCopyInto(out *TechnitiumCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TechnitiumCluster.
func (in *TechnitiumCluster) DeepCopy() *TechnitiumCluster {
	if in == nil {
		return nil
	}
	out := new(TechnitiumCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TechnitiumCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TechnitiumClusterList) DeepCopyInto(out *TechnitiumClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TechnitiumCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TechnitiumClusterList.
func (in *TechnitiumClusterList) DeepCopy() *TechnitiumClusterList {
	if in == nil {
		return nil
	}
	out := new(TechnitiumClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TechnitiumClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TechnitiumClusterNodeStatus) DeepCopyInto(out *TechnitiumClusterNodeStatus) {
	*out = *in
	if in.LastSynced != nil {
		in, out := &in.LastSynced, &out.LastSynced
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TechnitiumClusterNodeStatus.
func (in *TechnitiumClusterNodeStatus) DeepCopy() *TechnitiumClusterNodeStatus {
	if in == nil {
		return nil
	}
	out := new(TechnitiumClusterNodeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TechnitiumClusterServiceSpec) DeepCopyInto(out *TechnitiumClusterServiceSpec) {
	*out = *in
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TechnitiumClusterServiceSpec.
func (in *TechnitiumClusterServiceSpec) DeepCopy() *TechnitiumClusterServiceSpec {
	if in == nil {
		return nil
	}
	out := new(TechnitiumClusterServiceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TechnitiumClusterSpec) DeepCopyInto(out *TechnitiumClusterSpec) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	in.Storage.DeepCopyInto(&out.Storage)
	in.Resources.DeepCopyInto(&out.Resources)
	in.Service.DeepCopyInto(&out.Service)
	if in.AdminSecretRef != nil {
		in, out := &in.AdminSecretRef, &out.AdminSecretRef
		*out = new(SecretReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TechnitiumClusterSpec.
func (in *TechnitiumClusterSpec) DeepCopy() *TechnitiumClusterSpec {
	if in == nil {
		return nil
	}
	out := new(TechnitiumClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TechnitiumClusterStatus) DeepCopyInto(out *TechnitiumClusterStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Nodes != nil {
		in, out := &in.Nodes, &out.Nodes
		*out = make([]TechnitiumClusterNodeStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TechnitiumClusterStatus.
func (in *TechnitiumClusterStatus) DeepCopy() *TechnitiumClusterStatus {
	if in == nil {
		return nil
	}
	out := new(TechnitiumClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TechnitiumClusterStorageSpec) DeepCopyInto(out *TechnitiumClusterStorageSpec) {
	*out = *in
	out.Size = in.Size.DeepCopy()
	if in.StorageClassName != nil {
		in, out := &in.StorageClassName, &out.StorageClassName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TechnitiumClusterStorageSpec.
func (in *TechnitiumClusterStorageSpec) DeepCopy() *TechnitiumClusterStorageSpec {
	if in == nil {
		return nil
	}
	out := new(TechnitiumClusterStorageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Zone) DeepCopyInto(out *Zone) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Zone.
func (in *Zone) DeepCopy() *Zone {
	if in == nil {
		return nil
	}
	out := new(Zone)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Zone) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZoneList) DeepCopyInto(out *ZoneList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Zone, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZoneList.
func (in *ZoneList) DeepCopy() *ZoneList {
	if in == nil {
		return nil
	}
	out := new(ZoneList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ZoneList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZoneSpec) DeepCopyInto(out *ZoneSpec) {
	*out = *in
	out.ServerRef = in.ServerRef
	if in.PrimaryNameServerAddresses != nil {
		in, out := &in.PrimaryNameServerAddresses, &out.PrimaryNameServerAddresses
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Forwarder != nil {
		in, out := &in.Forwarder, &out.Forwarder
		*out = new(string)
		**out = **in
	}
	if in.ForwarderProtocol != nil {
		in, out := &in.ForwarderProtocol, &out.ForwarderProtocol
		*out = new(ForwarderProtocol)
		**out = **in
	}
	if in.Catalog != nil {
		in, out := &in.Catalog, &out.Catalog
		*out = new(string)
		**out = **in
	}
	if in.DNSSECValidation != nil {
		in, out := &in.DNSSECValidation, &out.DNSSECValidation
		*out = new(bool)
		**out = **in
	}
	if in.ForwarderProxy != nil {
		in, out := &in.ForwarderProxy, &out.ForwarderProxy
		*out = new(ForwarderProxy)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZoneSpec.
func (in *ZoneSpec) DeepCopy() *ZoneSpec {
	if in == nil {
		return nil
	}
	out := new(ZoneSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZoneStatus) DeepCopyInto(out *ZoneStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZoneStatus.
func (in *ZoneStatus) DeepCopy() *ZoneStatus {
	if in == nil {
		return nil
	}
	out := new(ZoneStatus)
	in.DeepCopyInto(out)
	return out
}
