/*
Copyright (c) 2026 Chris

Licensed under the MIT License. See the LICENSE file in the project root for
the full license text.
*/

// Command chartgen regenerates the Helm chart's CRD, RBAC and webhook templates
// from the controller-gen and kubebuilder output under config/, so the chart
// cannot drift from the API.
//
// Bodies (CRD spec, RBAC rules, webhook lists) are copied verbatim from config/;
// only the metadata is rewritten to use Helm values and helpers.
//
// With -check-rendered it instead reads `helm template` output on stdin and
// verifies the rendered chart matches config/.
package main

import (
	"bytes"
	"errors"
	"flag"
	"fmt"
	"io"
	"maps"
	"os"
	"path/filepath"
	"reflect"
	"slices"
	"strings"

	"sigs.k8s.io/yaml"
)

const header = "# Code generated by hack/chartgen from config/. DO NOT EDIT.\n# Regenerate with `just manifests`.\n"

type paths struct {
	config string
	chart  string
}

func main() {
	var p paths
	var checkRendered bool
	flag.StringVar(&p.config, "config", "config", "kustomize config directory")
	flag.StringVar(&p.chart, "chart", "charts/technitium-operator", "Helm chart directory")
	flag.BoolVar(&checkRendered, "check-rendered", false,
		"verify `helm template` output read from stdin (with webhooks and helper roles enabled) against config/")
	flag.Parse()

	var err error
	if checkRendered {
		err = verifyRendered(p, os.Stdin)
	} else {
		err = generate(p)
	}
	if err != nil {
		fmt.Fprintln(os.Stderr, "chartgen:", err)
		os.Exit(1)
	}
}

func generate(p paths) error {
	if err := generateCRDs(p); err != nil {
		return fmt.Errorf("CRDs: %w", err)
	}
	if err := generateManagerRBAC(p); err != nil {
		return fmt.Errorf("manager RBAC: %w", err)
	}
	if err := generateHelperRoles(p); err != nil {
		return fmt.Errorf("helper roles: %w", err)
	}
	if err := generateWebhooks(p); err != nil {
		return fmt.Errorf("webhooks: %w", err)
	}
	return nil
}

type objectMeta struct {
	Name        string            `json:"name"`
	Annotations map[string]string `json:"annotations"`
}

type object struct {
	Kind     string     `json:"kind"`
	Metadata objectMeta `json:"metadata"`
}

// readSource reads a controller-gen/kubebuilder YAML file. Sources must not
// contain Helm template delimiters, since they are pasted into templates.
func readSource(path string) ([]byte, error) {
	b, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	if bytes.Contains(b, []byte("{{")) {
		return nil, fmt.Errorf("%s contains `{{`, which Helm would interpret as a template action", path)
	}
	return b, nil
}

// bodyFrom returns doc from the top-level line `key:` onwards.
func bodyFrom(doc, key, path string) (string, error) {
	marker := "\n" + key + ":\n"
	i := strings.Index(doc, marker)
	if i < 0 {
		return "", fmt.Errorf("%s: no top-level %q field", path, key)
	}
	return strings.TrimRight(doc[i+1:], "\n") + "\n", nil
}

// splitDocs splits a multi-document YAML file, dropping empty documents.
func splitDocs(b []byte) []string {
	var docs []string
	for d := range strings.SplitSeq(string(b), "\n---\n") {
		d = strings.TrimPrefix(d, "---\n")
		if strings.TrimSpace(d) != "" {
			docs = append(docs, "\n"+d)
		}
	}
	return docs
}

func writeFile(path string, content string) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	return os.WriteFile(path, []byte(content), 0o644)
}

func generateCRDs(p paths) error {
	srcs, err := filepath.Glob(filepath.Join(p.config, "crd", "bases", "*.yaml"))
	if err != nil {
		return err
	}
	if len(srcs) == 0 {
		return errors.New("no CRDs found under config/crd/bases")
	}

	// The directory is entirely generated: remove templates for CRDs that no longer exist.
	outDir := filepath.Join(p.chart, "templates", "crds")
	if err := os.RemoveAll(outDir); err != nil {
		return err
	}

	for _, src := range srcs {
		b, err := readSource(src)
		if err != nil {
			return err
		}
		var crd object
		if err := yaml.Unmarshal(b, &crd); err != nil {
			return fmt.Errorf("%s: %w", src, err)
		}
		if crd.Kind != "CustomResourceDefinition" || crd.Metadata.Name == "" {
			return fmt.Errorf("%s: not a named CustomResourceDefinition", src)
		}
		spec, err := bodyFrom(string(b), "spec", src)
		if err != nil {
			return err
		}

		var out strings.Builder
		out.WriteString(header)
		out.WriteString("{{- if .Values.crds.install }}\n")
		out.WriteString("apiVersion: apiextensions.k8s.io/v1\n")
		out.WriteString("kind: CustomResourceDefinition\n")
		out.WriteString("metadata:\n")
		fmt.Fprintf(&out, "  name: %s\n", crd.Metadata.Name)
		out.WriteString("  annotations:\n")
		for _, k := range slices.Sorted(maps.Keys(crd.Metadata.Annotations)) {
			fmt.Fprintf(&out, "    %s: %s\n", k, crd.Metadata.Annotations[k])
		}
		out.WriteString("    {{- if .Values.crds.keep }}\n")
		out.WriteString("    helm.sh/resource-policy: keep\n")
		out.WriteString("    {{- end }}\n")
		out.WriteString("  labels:\n")
		out.WriteString("    {{- include \"technitium-operator.labels\" . | nindent 4 }}\n")
		out.WriteString(spec)
		out.WriteString("{{- end }}\n")

		if err := writeFile(filepath.Join(outDir, filepath.Base(src)), out.String()); err != nil {
			return err
		}
	}
	return nil
}

func generateManagerRBAC(p paths) error {
	src := filepath.Join(p.config, "rbac", "role.yaml")
	b, err := readSource(src)
	if err != nil {
		return err
	}
	rules, err := bodyFrom(string(b), "rules", src)
	if err != nil {
		return err
	}

	content := header + `{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "technitium-operator.fullname" . }}-manager-role
  labels:
    {{- include "technitium-operator.labels" . | nindent 4 }}
` + rules + `---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "technitium-operator.fullname" . }}-manager-rolebinding
  labels:
    {{- include "technitium-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "technitium-operator.fullname" . }}-manager-role
subjects:
- kind: ServiceAccount
  name: {{ include "technitium-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
`
	return writeFile(filepath.Join(p.chart, "templates", "manager-rbac.yaml"), content)
}

// helperRoleSources returns the kubebuilder-scaffolded admin/editor/viewer
// ClusterRoles, which are offered to cluster admins and unused by the manager.
func helperRoleSources(p paths) ([]string, error) {
	var srcs []string
	for _, role := range []string{"admin", "editor", "viewer"} {
		m, err := filepath.Glob(filepath.Join(p.config, "rbac", "*_"+role+"_role.yaml"))
		if err != nil {
			return nil, err
		}
		srcs = append(srcs, m...)
	}
	slices.Sort(srcs)
	if len(srcs) == 0 {
		return nil, errors.New("no *_{admin,editor,viewer}_role.yaml found under config/rbac")
	}
	return srcs, nil
}

func generateHelperRoles(p paths) error {
	srcs, err := helperRoleSources(p)
	if err != nil {
		return err
	}

	var out strings.Builder
	out.WriteString(header)
	out.WriteString("{{- if and .Values.rbac.create .Values.rbac.helperRoles }}\n")
	for _, src := range srcs {
		b, err := readSource(src)
		if err != nil {
			return err
		}
		var role object
		if err := yaml.Unmarshal(b, &role); err != nil {
			return fmt.Errorf("%s: %w", src, err)
		}
		if role.Kind != "ClusterRole" || role.Metadata.Name == "" {
			return fmt.Errorf("%s: not a named ClusterRole", src)
		}
		doc := string(b)
		rules, err := bodyFrom(doc, "rules", src)
		if err != nil {
			return err
		}
		// Keep the scaffolded comment explaining what the role is for.
		comment, _, _ := strings.Cut(doc, "\napiVersion:")
		comment = strings.TrimSpace(comment)

		out.WriteString("---\n")
		if comment != "" {
			out.WriteString(comment + "\n")
		}
		out.WriteString("apiVersion: rbac.authorization.k8s.io/v1\n")
		out.WriteString("kind: ClusterRole\n")
		out.WriteString("metadata:\n")
		fmt.Fprintf(&out, "  name: {{ include \"technitium-operator.fullname\" . }}-%s\n", role.Metadata.Name)
		out.WriteString("  labels:\n")
		out.WriteString("    {{- include \"technitium-operator.labels\" . | nindent 4 }}\n")
		out.WriteString(rules)
	}
	out.WriteString("{{- end }}\n")
	return writeFile(filepath.Join(p.chart, "templates", "helper-roles.yaml"), out.String())
}

type webhookConfig struct {
	Kind     string `json:"kind"`
	Webhooks []struct {
		Name string `json:"name"`
	} `json:"webhooks"`
}

// Lines in controller-gen's webhook output that the chart templates.
var webhookSubstitutions = []struct{ from, to string }{
	{"      namespace: system\n", "      namespace: {{ .Release.Namespace }}\n"},
	{"  failurePolicy: Fail\n", "  failurePolicy: {{ .Values.webhook.failurePolicy }}\n"},
}

func generateWebhooks(p paths) error {
	src := filepath.Join(p.config, "webhook", "manifests.yaml")
	b, err := readSource(src)
	if err != nil {
		return err
	}

	names := map[string]string{
		"MutatingWebhookConfiguration":   "mutating-webhook-configuration",
		"ValidatingWebhookConfiguration": "validating-webhook-configuration",
	}

	var out strings.Builder
	out.WriteString(header)
	out.WriteString("{{- if .Values.webhook.enabled }}\n")
	for _, doc := range splitDocs(b) {
		var cfg webhookConfig
		if err := yaml.Unmarshal([]byte(doc), &cfg); err != nil {
			return fmt.Errorf("%s: %w", src, err)
		}
		name, ok := names[cfg.Kind]
		if !ok {
			return fmt.Errorf("%s: unexpected kind %q", src, cfg.Kind)
		}
		body, err := bodyFrom(doc, "webhooks", src)
		if err != nil {
			return err
		}
		for _, s := range webhookSubstitutions {
			if n := strings.Count(body, s.from); n != len(cfg.Webhooks) {
				return fmt.Errorf("%s: %s: expected %d occurrences of %q, found %d",
					src, cfg.Kind, len(cfg.Webhooks), strings.TrimSpace(s.from), n)
			}
			body = strings.ReplaceAll(body, s.from, s.to)
		}

		out.WriteString("---\n")
		out.WriteString("apiVersion: admissionregistration.k8s.io/v1\n")
		fmt.Fprintf(&out, "kind: %s\n", cfg.Kind)
		out.WriteString("metadata:\n")
		fmt.Fprintf(&out, "  name: {{ include \"technitium-operator.fullname\" . }}-%s\n", name)
		out.WriteString("  labels:\n")
		out.WriteString("    {{- include \"technitium-operator.labels\" . | nindent 4 }}\n")
		out.WriteString("  {{- if .Values.webhook.certManager.enabled }}\n")
		out.WriteString("  annotations:\n")
		out.WriteString("    cert-manager.io/inject-ca-from: " +
			"{{ .Release.Namespace }}/{{ include \"technitium-operator.fullname\" . }}-serving-cert\n")
		out.WriteString("  {{- end }}\n")
		out.WriteString(body)
	}
	out.WriteString("{{- end }}\n")
	return writeFile(filepath.Join(p.chart, "templates", "webhook-configurations.yaml"), out.String())
}

// renderedObject is the subset of a rendered manifest that verifyRendered compares.
type renderedObject struct {
	Kind     string     `json:"kind"`
	Metadata objectMeta `json:"metadata"`
	Rules    []any      `json:"rules"`
	Webhooks []webhook  `json:"webhooks"`
}

type webhook struct {
	Name         string `json:"name"`
	ClientConfig struct {
		Service struct {
			Path string `json:"path"`
		} `json:"service"`
	} `json:"clientConfig"`
	Rules []any `json:"rules"`
}

func parseObjects(b []byte, src string) ([]renderedObject, error) {
	var objs []renderedObject
	for _, doc := range splitDocs(b) {
		var o renderedObject
		if err := yaml.Unmarshal([]byte(doc), &o); err != nil {
			return nil, fmt.Errorf("%s: %w", src, err)
		}
		if o.Kind != "" {
			objs = append(objs, o)
		}
	}
	return objs, nil
}

func loadObjects(files ...string) ([]renderedObject, error) {
	var objs []renderedObject
	for _, f := range files {
		b, err := os.ReadFile(f)
		if err != nil {
			return nil, err
		}
		o, err := parseObjects(b, f)
		if err != nil {
			return nil, err
		}
		objs = append(objs, o...)
	}
	return objs, nil
}

// verifyRendered checks rendered chart output against config/ semantically:
// the same CRDs, manager rules, webhooks and helper roles.
func verifyRendered(p paths, r io.Reader) error {
	b, err := io.ReadAll(r)
	if err != nil {
		return err
	}
	rendered, err := parseObjects(b, "stdin")
	if err != nil {
		return err
	}
	byKind := func(objs []renderedObject, kind string) []renderedObject {
		var out []renderedObject
		for _, o := range objs {
			if o.Kind == kind {
				out = append(out, o)
			}
		}
		return out
	}
	var problems []string

	// CRDs.
	crdFiles, err := filepath.Glob(filepath.Join(p.config, "crd", "bases", "*.yaml"))
	if err != nil {
		return err
	}
	wantCRDs, err := loadObjects(crdFiles...)
	if err != nil {
		return err
	}
	names := func(objs []renderedObject) []string {
		n := make([]string, 0, len(objs))
		for _, o := range objs {
			n = append(n, o.Metadata.Name)
		}
		slices.Sort(n)
		return n
	}
	if want, got := names(wantCRDs), names(byKind(rendered, "CustomResourceDefinition")); !slices.Equal(want, got) {
		problems = append(problems, fmt.Sprintf("CRDs: want %v, rendered %v", want, got))
	}

	// ClusterRoles: the manager role plus one per helper role.
	roleSrcs, err := helperRoleSources(p)
	if err != nil {
		return err
	}
	wantRoles, err := loadObjects(append([]string{filepath.Join(p.config, "rbac", "role.yaml")}, roleSrcs...)...)
	if err != nil {
		return err
	}
	gotRoles := byKind(rendered, "ClusterRole")
	for _, want := range wantRoles {
		idx := slices.IndexFunc(gotRoles, func(o renderedObject) bool {
			return strings.HasSuffix(o.Metadata.Name, "-"+want.Metadata.Name)
		})
		switch {
		case idx < 0:
			problems = append(problems, fmt.Sprintf("ClusterRole *-%s: not rendered", want.Metadata.Name))
		case !reflect.DeepEqual(want.Rules, gotRoles[idx].Rules):
			problems = append(problems, fmt.Sprintf("ClusterRole *-%s: rules differ from config/rbac", want.Metadata.Name))
		}
	}

	// Webhooks.
	wantHooks, err := loadObjects(filepath.Join(p.config, "webhook", "manifests.yaml"))
	if err != nil {
		return err
	}
	for _, want := range wantHooks {
		got := byKind(rendered, want.Kind)
		if len(got) != 1 {
			problems = append(problems, fmt.Sprintf("%s: rendered %d, want 1", want.Kind, len(got)))
			continue
		}
		if !reflect.DeepEqual(webhookSummary(want.Webhooks), webhookSummary(got[0].Webhooks)) {
			problems = append(problems, fmt.Sprintf("%s: webhooks differ from config/webhook", want.Kind))
		}
	}

	if len(problems) > 0 {
		return fmt.Errorf("rendered chart does not match config/:\n  %s", strings.Join(problems, "\n  "))
	}
	fmt.Printf("Rendered chart matches config/: %d CRDs, %d ClusterRoles, %d webhook configurations\n",
		len(wantCRDs), len(wantRoles), len(wantHooks))
	return nil
}

// webhookSummary keys webhooks by name, keeping the fields the chart must not change.
func webhookSummary(hooks []webhook) map[string]any {
	m := map[string]any{}
	for _, h := range hooks {
		m[h.Name] = []any{h.ClientConfig.Service.Path, h.Rules}
	}
	return m
}
