{{- if .Values.webhook.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: webhook-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "technitium-operator.labels" . | nindent 4 }}
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: {{ .Values.webhook.port }}
  selector:
    {{- include "technitium-operator.selectorLabels" . | nindent 4 }}
{{- if .Values.webhook.certManager.enabled }}
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "technitium-operator.fullname" . }}-selfsigned-issuer
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "technitium-operator.labels" . | nindent 4 }}
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "technitium-operator.fullname" . }}-serving-cert
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "technitium-operator.labels" . | nindent 4 }}
spec:
  dnsNames:
  - webhook-service.{{ .Release.Namespace }}.svc
  - webhook-service.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: {{ include "technitium-operator.fullname" . }}-selfsigned-issuer
  secretName: webhook-server-cert
{{- end }}
{{- end }}
